services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    privileged: true  # Allow the container to modify system settings
    environment:
      - LANG=en
      - WG_HOST=${WG_HOST}
      - PASSWORD_HASH=${PASSWORD_HASH}
      - PORT=51821
      - WG_PORT=51820
    volumes:
      - /home/dev/.wg-easy:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    ports:
      - 51821:51821/tcp
      - 51820:51820/udp
    healthcheck:
      test:
        - CMD
        - wg
        - show
        - wg0
        - dump
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 20s
    dns:
      - 1.1.1.1  # Cloudflare DNS
      - 8.8.8.8  # Google DNS
    networks:
      - wg-easy-network

networks:
  wg-easy-network:
    external: true
